### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by ndowens** [necco889/CombatInsights#1] opened 2024-11-09 02:43 UTC
CombatInsights use to pop up along with CMX, but it is no longer doing that. Is there any other way to get it to pop up?

**Comment by necco889** [comment] 2024-11-09 08:20
Thanks for letting me know, the issue was caused by the bad zip file structure uploaded to esoui.com so Minion misplaced the files. Should be fixed in version 1.1.1

**Closed as completed** 2024-11-09 08:20 UTC
